# Generated by Django 6.1.1 on 2026-09-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
