# Generated by Django 6.1.1 on 2026-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=50)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('conflicting_event_id', models.IntegerField(blank=True, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Prevented', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
