# Generated by Django 6.1.1 on 2026-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
