# Generated by Django 6.1.1 on 2026-09-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
