# Generated by Django 6.1.1 on 2026-09-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('resource_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
