# Generated by Django 6.1.1 on 2026-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
