# Generated by Django 6.1.1 on 2026-09-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('request_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('requested_by', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
